spring.application.name=hospitalManagement

# DB configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.servlet.context-path=/api/v1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Data initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
#spring.sql.init.data-locations=classpath:data.sql

#security config
#spring.security.user.name = kshitij
#spring.security.user.password = kshitij

#we can define our roles here as an array but better to do this in db or in config


jwt.secret.key=asddfeir4ui4ui3nfnam1sfkjdljsdklj4343rjjdfnsfk

#oauth2 client properties
spring.security.oauth2.client.registration.google.client-id = aslfdlas
spring.security.oauth2.client.registration.google.client-secret = asdsdfs


spring.security.oauth2.client.registration.github.client-id = aslfdlas
spring.security.oauth2.client.registration.github.client-secret = asdsdfs
